{{- if and .Values.udrive.auth (not .Values.udrive.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unity-office.fullname" . }}-udrive
  labels:
    {{- include "unity-office.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.udrive.auth.usernameKey | default "username" }}: {{ .Values.udrive.auth.username | quote }}
  {{ .Values.udrive.auth.passwordKey | default "password" }}: {{ .Values.udrive.auth.password | quote }}
{{- end }}
